### ISSUE TITLE
File not found: 'jwaWinCrypt.dcu'

### ISSUE THREAD

**Issue by progressify** [SinavAhmet/BasicRdp#2]
Hi, 
I have downloaded the zip file and extracted the source code in my source folder.
I have copied and pasted the code in the readme files, but I receive this error:

```File not found: `'jwaWinCrypt.dcu'```

Can you help me?

**Comment by SinavAhmet** [comment]
Try to clean and build. If not done pls comment here.

**Comment by progressify** [comment]
nope, i have created a new project and I have the same problem
but in your code I don't see any file with this name.

what is the problem?

**Comment by progressify** [comment]
up, any idea?

**Comment by SinavAhmet** [comment]
hi there,
JwaWinCrypt.pas commited. Get that file and recompile your project. 
If u face any issue inform me.

**Comment by progressify** [comment]
this is the line that gives me a new error:

`{$I ..\Includes\JediAPILib.inc}`

and this is the error:

`[Fatal Error] jwaWinCrypt.pas(48): File not found: '..\Includes\JediAPILib.inc'`

:( sorry if I bother you

EDIT:
I have found the JediAPILib.inc and I have fixed the path, but now in JediAPILib.inc at this line:

`{$I ..\Includes\jedi.inc}`

and this is the error:

`[Fatal Error] JediAPILib.inc(46): File not found: '..\Includes\jedi.inc'`

EDIT2:
ok, I have resolved all the conflict:
https://github.com/graemeg/freepascal/blob/master/packages/winunits-jedi/src/jwawinbase.pas
https://github.com/project-jedi/jedi/blob/master/jedi.inc
https://github.com/frones/ACBr/blob/master/Fontes/Terceiros/JediWin32API/JwaNtStatus.pas
https://github.com/magicmonty/delphi-code-coverage/blob/master/3rdParty/JWAPI/jwapi2.2a/Win32API/JwaWinType.pas
https://sourceforge.net/p/dxbx/svn/1629/tree/Source/Delphi/Libraries/Jwapi/Win32API/JwaWinNT.pas#l9754
https://github.com/RRUZ/wmi-delphi-code-creator/blob/master/Delphi/JwaWinDLLNames.pas

this is all the missing library, pls add it to the project.

the function BlobDataToHexStr was missing in the code, here I have found the function:
https://github.com/carono/utils/blob/master/CryptRDP.pas

I have another error, I hope the last xD 

`ShellExecute(0,'open','mstsc.exe',PWideChar(s),nil,SW_SHOWNORMAL);`

```
[Warning] rdpform.pas(107): Suspicious typecast of String to PWideChar
[Error] rdpform.pas(107): Incompatible types: 'WideChar' and 'Char'
```

you know why?
ty

**Comment by SinavAhmet** [comment]
it may be about delphi version. change to PWideChar to PChar.

**Comment by progressify** [comment]
Wow, thank you
Now it compiles!!!

For test it I must to call:
`procedure CnnRdp(user,pass,srv,dmn:String)`
in `FormCreate ` event, for example, right?

**Comment by SinavAhmet** [comment]
yes u can put it on button click event or where u want. 
CnnRdp writes the rdp file to disk so if any authorization 
problem u can fail. So beware about that.

**Comment by progressify** [comment]
🤔 It write only the file? 
If I want to see the remote desktop?

**Comment by SinavAhmet** [comment]
it is write file a.rdp, and the procedure pass that file as parameter to mstsc.exe.
when u run u will see rdp.

**Comment by progressify** [comment]
ahhh ok
this evening I will try

See you soon
For missing library, you accept pull requests?

**Comment by SinavAhmet** [comment]
yes sure

**Comment by progressify** [comment]
See the changes :)

**Comment by SinavAhmet** [comment]
Tnks. All corrected now perfectly.

**Comment by SinavAhmet** [comment]
All done
